export const LOAD_SESSION_SUCCESS = 'LOAD_SESSION_SUCCESS'
export const REMOVE_SESSION = 'REMOVE_SESSION'

export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_ERROR = 'API_CALL_ERROR'

//users
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER_OPTIMISTIC = 'DELETE_USER_OPTIMISTIC'