export const LOAD_SESSION_SUCCESS = 'LOAD_SESSION_SUCCESS'
export const LOAD_SESSION_PARSE_SUCCESS = 'OAD_SESSION_PARSE_SUCCESS'
export const REMOVE_SESSION = 'REMOVE_SESSION'

export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_ERROR = 'API_CALL_ERROR'

//users TODO smooth out create user functionality in app
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const DELETE_USER_OPTIMISTIC = 'DELETE_USER_OPTIMISTIC'

//bank accounts
export const LOAD_BANK_ACCOUNTS_SUCCESS = 'LOAD_BANK_ACCOUNTS_SUCCESS'
export const CREATE_BANK_ACCOUNT_SUCCESS = 'CREATE_BANK_ACCOUNT_SUCCESS'
export const DELETE_BANK_ACCOUNT_SUCCESS = 'DELETE BANK ACCONT_SUCCESS'

//roles
export const LOAD_ALL_ROLES_SUCCESS = 'LOAD_ALL_ROLES_SUCCESS'
export const LOAD_USERS_FOR_ROLE = 'LOAD_USERS_FOR_ROLE'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const REMOVE_USER_SUCESSS = 'REMOVE_USER_SUCCESS'