export const LOAD_SESSION_SUCCESS = 'LOAD_SESSION_SUCCESS'
export const REMOVE_SESSION = 'REMOVE_SESSION'

export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_ERROR = 'API_CALL_ERROR'

//accounts
export const LOAD_ACCOUNTS_SUCCESS = 'LOAD_ACCOUNTS_SUCCESS'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_OPTIMISTIC = 'DELETE_ACCOUNT_OPTIMISTIC'